### ISSUE TITLE
Add documents for purchase and deliveries

### ISSUE THREAD

**Issue by ElonLP** [ArnesSI/netbox-inventory#193]
### Feature Request:

It would be highly beneficial if the NetBox-Inventory plugin allowed attaching documents such as quotes, order confirmations, and delivery notes to purchases and deliveries. This feature would centralize relevant documentation, making it easier to track and manage procurement and delivery processes within NetBox.

Thank you for considering this enhancement!

**Comment by cs-1** [comment]
Hi @ElonLP,

I would definitely not recommend going down that road because NetBox is very bad at managing documents. When deleting assets or purchases, there's a really high chance that you will accumulate tons of orphaned files on your NetBox server. But there's an elegant way to solve this using Custom Links and your own cloud like ownCloud or nextCloud (or any other cloud, for that matter). Let's take purchases as an example: you go to "Customization > Custom Links" and create a new custom link. Select "NetBox Inventory > Purchase" as "Object types". Create a directory on your cloud server where you'll store documents for a purchase, let's say `https://my.example.cloud.com/purchases`. Tick the "New window" checkbox in the custom link. Enter "Purchase documents" as "Link text" (this will be the label on the button in your purchase view).  Let's say you want to store documents for purchase "12345". Create the directory `https://my.example.cloud.com/purchases/12345` in your cloud. Now set "Link URL" in your custom link to

```jinja
https://my.example.cloud.com/purchases//{{ object.name }}
```
This will correctly set the URL to the links directory to the name of the purchase. Save the custom link. From now on, a button "Purchase documents" will show up in your purchases. When you click it, the correct cloud directory with the said purchase's documents will open up in a new browser window. Voilà!

**Comment by matejv** [comment]
as @cs-1 suggested - this seems like a good practice.

Alternative is the use of netbox attachments plugin - the use of which is now documented in the README.md
