### ISSUE TITLE
inventory plugin model ideas

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#2]
I was going to make the same plugin, but you beat me to it.

Would you like to collaborate here?  Myself and another netbox maintainer came up with a rough ideas for the models.

Your models also addressed items we did not originally think about, but are also super useful.

We approached it from the SFP space where you might have multiple similar 10G-LR optics, but from different vendors or just different model numbers that are all the same.

https://github.com/ryanmerolle/netbox-inventory/issues/1

Take a look at let me know how you want to proceed.  I'd be happy to help!

**Comment by matejv** [comment]
Thank you for taking an interest in our plugin :D We're still adding a couple features and we need to polish the UI a bit, but it should be mostly usable for testing.

Let me give a bit of background on our motivations behind developing it.

We're in the process if implementing netbox as a source of truth for multiple parts of our network. But we also have a custom in-house tool for another large network segment, where netbox just is not a great fit.

The amount of equipment we need to keep track of grew significantly in recent years and we wanted to implement a better inventory tracking solution.

We looked at [Snipe-IT](https://snipeitapp.com/) and some commercial asset tracking tools. After a while we figured it would be too much work trying to integrate a separate asset tracking tool and Netbox and our own tool, so we opted to write a netbox plugin instead.

The aim is to have this plugin be the single source of truth for all our assets. Whether they are used within netbox, in out tool or still in storage. That meant we want to be able to mark an Asset as "in use", even if it's not used within Netbox itself.

So our idea is to have an Asset model that contains all equipment that has a serial number, and we want to know stuff like when was it purchased, where is it installed and so on. It doesn't matter if it's a network device, a linecard, PSU, SFP module... Everything goes in one table to make it easier to gather and import data, make reports...

That's why our Asset model has foreign keys to `DeviceType`, `ModuleType` and `InventoryItemType` (only one of those keys can be set for a given Asset instance).

All that said, I also wanted to make this plugin useful to others. So all the features that we deemed specific to our use-case are optional and can be turned on or off via plugin's settings.

Definitely interested in collaboration / contributions / feedback. I looked at https://github.com/ryanmerolle/netbox-inventory/issues/1 and of course both plugins would have some common stuff.

The `AssetTypeGroup` model is an interesting idea, that we didn't think of. But I see where it would be useful. Having a quick answer to questions like "how many multimode SFP+ modules do we still have spare" would be a great selling point to our team :D We could even have a view/report with stuff that is close to running out.

We went a different way with `AssetType` though. We're just reusing netbox's `DeviceType` and `ModuleType` and just added `InventoryItemType`. I'm not 100% that was the right move, but I also don't want to duplicate for example "Cisco ASR-1001" in two tables. So I'm not sure what would be the way to go implementing `AssetTypeGroup` functionality.

I like the idea to be able to mass-add many similar assets. From netbox 3.3 the [clone feature](https://github.com/netbox-community/netbox/issues/9414) is improved I see. Also perhaps improve the create asset form to be able to specify a range of serial numbers? Like when adding interfaces to a device in netbox.

Also we have a list of possible improvements and features we still want to add in the README.

If you have any suggestions, questions or ideas what you'd like to contribute, I'd be happy to discuss further :)

**Comment by ryanmerolle** [comment]
Hello Matejv!  Thank you for starting down this development and even engaging me in discussion.

I think we are basically on the same page on functionality and high level reasons to build this plugin.  I too tried snipe-it and it did not fit the bill for anything but assets assigned to users.

@dansheps suggested a lot of the model I documented in that issue I linked.

The challenge with 'InventoryItem' is that it **MUST** be associated to a 'device'.  The same goes for  and 'InventoryItemType' as it **MUST** be associated to a 'devicetype'.  This will not work for inventorying sfps and cables not associated to a device.  That is why I did not suggest using them.  I think you are trying to also inventory loose SFPs and cables that may not be tied to a device or devicetype.  A consolidated view that includes `inventoryitems` probably still makes sense.

We do not need too many chefs in the kitchen building the base functionality.  I think for now my contributions can be in terms of the model discussion we are having hear.

After things settle and are agreed, I can look at reviewing, and tweaking on specific issues assuming I get your agreement on the approach of an issue.

**Comment by ryanmerolle** [comment]
I started testing the plugin in my lab netbox-docker.  I will raise some issues with issue I find.

**Comment by matejv** [comment]
There might be a miss-understanding how the plugin is intended to work. I've not documented this clearly in the README yet, sorry.

For a given device you also have an entry for Asset. Then you can link these two together. (the same applies to modules and inventoryItems).

Here is the entity relation diagram I quickly put together. Blue lines are relations defined by this plugin. 

![entity_netbox](https://user-images.githubusercontent.com/1256843/196126646-74310c9f-dc39-425f-8555-45982aa8fc87.png)

Every Asset has a link to `DeviceType` OR `ModuleType` OR `InventoryItemType` (exactly one of these 3 must be set). When you deploy this asset into the network you also set a FK to netbox `Device` OR `Module` OR `InventoryItem`.

Obviously this means that there are some redundant database relations in the model (for example netbox.Device doesn't need to link to DeviceType as this is already defined by Device > Asset > DeviceType; It also doesn't need Device.serial, since this is defined by Device > Asset.serial). However since we didn't want to go changing netbox database model, this was the best compromise :)


Out general workflow is planned to be:

- order equipment from supplier (usually we order a mix of devices, line cards and SFP modules in the same order)
- when equipment arrives, arrange data from the order in one CSV file
- import that CSV into Assets
- when I need to deploy a new device (or module or InventoryItem), I find it in assets table and select ether "Create from asset" (green button) or "Edit assignment" (orange button). See screenshot
![image](https://user-images.githubusercontent.com/1256843/196129786-41699835-84c0-497b-b93c-f9e132ee0bb9.png)

UI views and README needs a bit more help written to make this more obvious.

**Comment by ryanmerolle** [comment]
Apologies @matejv I was looking at the models and did not fully understand until I fired up a netbox-docker instance with the plugin installed.

I think this is a good intended workflow.  I threw in some issues for tracking bugs or workflow/model tweaks.

As I stated before, I would be happy to assist you with this.

For now, how about I build a PR for the README.md update for now?

**Comment by matejv** [comment]
I'm currently working on fixing the issues you pointed out and any others I find along the way.

If you're willing to flesh out the readme that would be a big help indeed!

**Comment by ryanmerolle** [comment]
If anything comes up you need help with or want someone to bounce ideas off of let me know.  I am on [https://netdev.chat](https://netdev.chat) with the same username
