### ISSUE TITLE
Create new model for inventorygroup

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#7]
The name is a placeholder until we can find something better.

This would allow us to group, filter, and count inventory items that share a common group.  This solves the question of how many 10g-lr sfps do I have no matter the brand/part number

**Comment by matejv** [comment]
I'm brainstorming how could we implement this.

Option 1: Ideally this would be a foreign key on DeviceType and ModuleType models. But as these are core netbox models, we can't change them. We can do it for InventoryItemType, since this is part of this plugin. This might be the simplest solution if we limit the scope to just inventory items. (Do we really need this feature on devices and modules?)

Option 2: Add a custom field or tags to DeviceType, ModuleType and InventoryItemType to denote "groups" of similar hardware. Upside is that it wouldn't require any database changes. However filtering or counting Assets per "group" might be difficult to implement (need to investigate).

Option 3: Add a group foreign key to Asset model. So every asset could belong to different groups. This might be more flexible, since one could use this groups in other ways as we envision. But it could be more difficult for users to manage data correctly (every time you create an Asset you need to know what group to assign).

Option 4: ?? :)

**Comment by lordspirit** [comment]
I'm up for this feature as well. My most wanted non-existing netbox feature is a simple part count for connectors - we use a ton here, like a simple rj45 plug or bnc rg6. I would love to know how to draw a CRUD for netbox but since i dont have enought knowledge this is the most similar one, and im thankfull for it. The option 1 should work, idk if is @ryanmerolle initial idea but i think it would work for me :)
An option to aggregate so we could simply remove X quantity or add Y quantity, tracking where is/was, what was used for it would be awesome!

**Comment by matejv** [comment]
I've implemented this in #40 Here's a sample screenshoot

![image](https://user-images.githubusercontent.com/1256843/206921985-cc394b0e-750a-4175-974b-545105621ebd.png)
