### ISSUE TITLE
Setup Github Actions pypi workflow

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#9]
Setup the project's pypi workflow so users can install from pypi.

**Comment by ryanmerolle** [comment]
This should wait on #8 being completed first since it adds a pypi project long_description.

**Comment by ryanmerolle** [comment]
Let me know if you need help here, but you just need to:

- Register a pypi account
- Grab your user key
- Add the action from the marketplace for pypi
- Copy your user key to a github secret per the instructions
- Initiate a release in github
- After your first release, you will see the project created in pypi
- From there you can generate a key for this project, and update the key so this project uses the pypi key for the project instead of your account

But again, I would wait on the #8 being ready.

**Comment by matejv** [comment]
Thank you for the steps. I have not used github actions before so that was useful!

I've replaced setup.py with pyproject.toml, as this seems to be the more [modern way](https://packaging.python.org/en/latest/tutorials/packaging-projects/) of specifying python package metadata now. It will also pick up the README automatically so no need to read the file into long_description, which is a plus :)
